INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (1, 'Samsung', 'Korea Południowa', '1938-05-05','https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/1024px-Samsung_Logo.svg.png');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (2, 'Apple', 'USA', '1976-04-01','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (3, 'Motorola', 'USA', '1928-09-25','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Motorola_M_symbol_blue.svg/1200px-Motorola_M_symbol_blue.svg.png');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (4, 'Huawei', 'Chiny', '1987-09-15','https://logofirmy.net/wp-content/uploads/2020/04/Huawei-Logo.png');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (5, 'Xiaomi', 'Chiny', '2010-04-06','https://galeriamlociny.pl/app/uploads/wayfinder/url_logo/3144.png');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (6, 'Sony', 'Japonia', '1946-05-07','https://motogaraz.in/wp-content/uploads/2016/07/sony-logo.jpg');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (7, 'HTC', 'Chiny', '1997-05-15','https://www.telepolis.pl/images/2020/02/htc-logo.jpg');
INSERT INTO producer(ID, NAME, COUNTRY, DATE_OF_CREATION, LOGO_URL) VALUES (8, 'OnePlus', 'Chiny', '2013-12-16','https://mobileworld24.pl/wp-content/uploads/2020/03/OnePlus-logo-2020.jpg');

INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(1, 'Galaxy S20+', 6.7, 8, 128, 3, 12, 1, 10, 4500, 'Exynos 990', 'https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2020/2/pr_2020_2_11_8_29_55_187_00.jpg' );
INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(1, 'Galaxy S10', 6.1, 8, 128, 3, 12, 1, 10, 3400, 'Exynos 9820', 'https://stat-m8.ms-online.pl/media/cache/gallery/rc/p24ltytj/images/20/20853450/sm-g973-galaxys10-front-green-1.jpg' );
INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(1, 'Galaxy M21', 6.4, 4, 64, 3, 48, 1, 20, 6000, 'Exynos 9611', 'https://www.mediaexpert.pl/media/cache/gallery/images/23/2338806/Smartfon-SAMSUNG-Galaxy-M21-Czarny-front-tyl.jpg');
INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(1, 'Galaxy A71', 6.7, 6, 128, 4, 65, 1, 20, 4500, 'SnapDragon 730', 'https://image.ceneostatic.pl/data/products/90356847/i-samsung-galaxy-a71-sm-a715-128gb-czarny.jpg' );


INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(2, 'Iphone Xs', 5.85, 4, 64, 2, 12, 1, 7, 2660, 'A12', 'https://image.ceneostatic.pl/data/products/69539143/i-apple-iphone-xs-64gb-srebrny.jpg');
INSERT INTO smartphone(PRODUCER_ID, MODEL, SCREEN_SIZE, RAM, STORAGE, REAR_CAMERAS, MAIN_REAR_CAMERA_RESOLUTION, FRONT_CAMERAS, MAIN_FRONT_CAMERA_RESOLUTION, BATTERY_CAPACITY, PROCESSOR, IMAGE_URL) VALUES(2, 'Iphone 11 Pro Max', 6.5, 4, 64, 3, 12, 1, 12, 3969, 'Exynos 990', 'https://stat-m7.ms-online.pl/media/cache/gallery/rc/efniyj8o/images/20/20982412/apple-iphone-11-pro-zloty-3.jpg');
